services:
  - type: web
    name: ecommerce-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: false
      - key: EMAIL_HOST_USER
        value: your-email@example.com
      - key: EMAIL_HOST_PASSWORD
        value: your-email-password
      - key: EMAIL_RECEIVING_USER
        value: your-email@example.com
